---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opencost
  namespace: opencost
spec:
  chart:
    spec:
      chart: opencost
      version: "1.28.2"
      sourceRef:
        kind: HelmRepository
        name: opencost
        namespace: opencost
  interval: 1h
  values:
    opencost:
      exporter:
        extraEnv:
          EMIT_KSM_V1_METRICS: "false"
          EMIT_KSM_V1_METRICS_ONLY: "true"
      prometheus:
        internal:
          enabled: true
          serviceName: kube-prometheus-stack-prometheus
          namespaceName: monitoring
      ui:
        enabled: true

      metrics:
        serviceMonitor:
          enabled: true
